name: ci

on:
  push:
  pull_request:


jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup CMake
      uses: lukka/get-cmake@latest

    - name: Setup Ninja
      uses: seanmiddleditch/gha-setup-ninja@v5

    - name: Install FFmpeg build prerequisites (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg pkg-config nasm yasm \
          libavformat-dev libavcodec-dev libavutil-dev libswresample-dev

    - name: Install FFmpeg build prerequisites (macOS)
      if: runner.os == 'macOS'
      run: |
        brew update
        brew install ffmpeg pkg-config nasm yasm

    - name: Clean build directory
      run: cmake -E rm -rf build/default

    - name: Configure
      run: cmake --preset default

    - name: Build
      run: cmake --build --preset default --parallel

    - name: Test
      run: ctest --preset default

    - name: Configure (No LibAV fallback)
      if: runner.os == 'Linux'
      run: cmake --preset nolibav

    - name: Build (No LibAV fallback)
      if: runner.os == 'Linux'
      run: cmake --build --preset nolibav --parallel

    - name: Test (No LibAV fallback)
      if: runner.os == 'Linux'
      run: ctest --preset nolibav
